name: Build FaryBooks APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v5

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compilar FaryBooks
        run: gradle assembleFullDebug assembleDemoDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: FaryBooks-APKs
          path: |
            app/build/outputs/apk/full/debug/app-full-debug.apk
            app/build/outputs/apk/demo/debug/app-demo-debug.apk
